apiVersion: v1 
kind: PersistentVolume
metadata:
  name: mongopv
  namespace: test-ns
spec:
  capacity:
    storage: 3Gi 
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /tmp
    

