apiVersion: apps/v1
kind: Deployment
metadata:
   name: hpadeployment
   namespace: test-ns
spec:
  selector:
     matchLabels:
        app: hpapod
  template:
    metadata:
       name: HPAPOD
       labels:
        app: hpapod
    spec:
      containers:
      - name: k8container
        image:  k8s.gcr.io/hpa-example
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            cpu: 500m
            memory: 250Mi
          limits:
            cpu: 1
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
      name: websvc
      namespace: test-ns
spec:
  type: NodePort
  selector:
      app: hpapod
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myhpaapp
  namespace: test-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpadeployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50

