apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        resources:
          requests:
            memory: "250Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: jenkinsvol
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkinsvol
        persistentVolumeClaim:
          claimName: jenkinspvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkinspvc
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Service
metadata:
  name: jenkinsservice
spec:
  type: NodePort 
  selector:
    app: jenkins
  ports:
  - port: 80
    targetPort: 8080



