apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec: 
  selector:
   matchLabels:
     app: jenkinspod
  template:
    metadata: 
      labels:
        app: jenkinspod
    spec: 
      containers:
      - name: jenkinscontainer
        image: jenkins/jenkins:lts
        resources:
          requests: 
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: jenkinsvol
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkinsvol
        persistentVolumeClaim:
          claimName: jenkinspvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: jenkinspvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
       storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  selector:
    app: jenkinspod  
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080