apiVersion: v1
kind: LimitRange
metadata:
  name: example-limit-range
  namespace: test-ns
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 1
    defaultRequest:
      memory: 256Mi
      cpu: 1
    type: Container

