apiVersion: v1
kind: Pod
metadata:
   name: webpod
   labels:
       app: mavenweb
spec:
 containers:
 - name: webcontainer
   image:  gangadockerhub/maven-web-application:2
   ports:
   - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
      name: websvc
spec:
  type: NodePort
  selector:
      app: mavenweb
  ports:
  - port: 80
    targetPort: 8080
