apiVersion: apps/v1
kind: Deployment
metadata:
   name: mavendeployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxUnavailable: 1 
       maxSurge: 1
  minReadySeconds: 30        
  selector:
     matchLabels:
       app: mavenwebapp
  template:
   metadata:
     name: mavenpod
     labels:
       app: mavenwebapp
   spec:
      containers:
      - name: mavencontainer
        image: dockerhandson/maven-web-application:1
        ports:
        - containerPort: 8080
        resources:
         requests:
           cpu: 250m
           memory: 300Mi
         limits:
           cpu: 500m
           memory: 500Mi       
---	
apiVersion: v1
kind: Service
metadata:
  name: mavensvc
spec:
  selector:
    app: mavenwebapp
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080   
