apiVersion: apps/v1
kind: Deployment
metadata:
   name: mavendeployment
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
     matchLabels:
       app: mavenwebapp
  template:
   metadata:
     name: mavenpod
     labels:
       app: mavenwebapp
   spec:
      containers:
      - name: mavencontainer
        image: dockerhandson/maven-web-application:22
        ports:
        - containerPort: 8080
---		 
apiVersion: v1
kind: Service
metadata:
  name: mavensvc
spec:
  selector:
    app: mavenwebapp
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080   
