apiVersion: v1
kind: Pod
metadata:
    name: webpod   
    labels:
      app: mavenweb
spec:
 containers:
 - name: nginxcontainer
   image: nginx
   ports: 
   - containerPort: 80
 - name: javawebcontainer
   image: dockerhandson/java-web-app:1
   ports:
   - containerPort: 8080
    
---
apiVersion: v1
kind: Service
metadata:
    name: websvc
spec:
  type: NodePort
  selector:
        app: mavenweb
  ports:
  - port: 80
    targetPort: 80
    name: nginx
  - port: 8080
    targetPort: 8080
    name: javaweb   

