apiVersion: apps/v1
kind: Deployment
metadata:
   name: mavendeployment
   namespace: test-ns
spec:
  replicas: 2
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxUnavailable: 2
       maxSurge: 1
  minReadySeconds: 30
  selector:
     matchLabels:
        app: mavenweb
  template:
    metadata:
       name: mavenpod
       labels:
        app: mavenweb
    spec:
      containers:
      - name: webcontainer
        image:  dockerhandson/maven-web-application:1
        ports:
        - containerPort: 8080
        resources:
          requests: 
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 1
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
      name: websvc
      namespace: test-ns
spec:
  type: NodePort
  selector:
      app: mavenweb
  ports:
  - port: 80
    targetPort: 8080

