apiVersion: v1 
kind: PersistentVolume
metadata:
  name: nfsvol
  namespace: test-ns
spec:
  capacity:
    storage: 4Gi 
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 10.128.0.57
    path: /mnt/nfs-share
