apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginxrs
spec:
  replicas: 2
  selector:
   matchLabels:
    app: nginxpod
  template:
   metadata:
    name: nginx
    labels:
        app: nginxpod
   spec:
    containers:
    - name: nginxcontainer
      image: nginx
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
     name: nginxsvc
spec:
 type: NodePort
 selector:
     app: nginxpod
 ports:
 - port: 80
   targetPort: 80

