apiVersion: v1
kind: Pod
metadata:
    name: ngnxpod
    namespace: test-ns
    labels:
      app: nginx
spec:
 containers:
 - name: nginxcontainer
   image: nginx
   ports:
   - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
     name: nginxsvc
     namespace: test-ns
spec:
 type: NodePort
 selector:
     app: nginx
 ports:
 - port: 80
   targetPort: 80


