apiVersion: v1
kind: Pod
metadata:
    name: ngnxandjavaweb
    labels:
      app: nginx-java
spec:
 containers:
 - name: nginxcontainer
   image: nginx
   ports:
   - containerPort: 80
 - name: javawebcontainer
   image: gangadockerhub/java-web-app:2
   ports:
   - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
     name: nginxsvcandjavawebsvc
spec:
 type: NodePort
 selector:
     app: nginx-java
 ports:
 - port: 80
   targetPort: 80
   name: nginxcontainer
 ports:
 - port: 80
   targetPort: 8080
   name: javawebcontainer
