apiVersion: v1
kind: ReplicationController
metadata:
  name: ngnxrc
spec:
  replicas: 1
  selector:
    app: ngnxpod
  template:
    metadata:
      name: nginxrcpod
      labels:
        app: ngnxpod
    spec:
      containers:
      - name: nginxcontainer
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginxrcsvc
spec:
  type: NodePort
  selector:
    app: ngnxpod
  ports:
  - port: 80
    targetPort: 80

