apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ngnxds
spec:
  selector:
    matchLabels:
      app: ngnxpod
  template:
    metadata:
      name: nginxrcpod
      labels:
        app: ngnxpod
    spec:
      containers:
      - name: nginxcontainer
        image: nginx
        ports:
        - containerPort: 80

