apiVersion: v1
kind: Pod
metadata:
  name: nodejspod
  labels:
    app: nodejs
  namespace: test-ns
spec:
  containers:
    - name: nodejs
      image: dockerhandson/node-app-mss:3
      ports:
        - containerPort: 9981
---
apiVersion: v1
kind: Service
metadata:
  name: nodejssvc
  namespace: test-ns
spec:
  selector:
    app: nodejs
  type: NodePort
  ports:
    - port: 80
      targetPort: 9981

