apiVersion: v1
kind: Pod
metadata:
    name: webpod2   
    labels:
      app: nodejs
    namespace: test-ns  
spec:
 containers:
 - name: webcontainer2
   image: dockerhandson/node-app-mss:3
   ports: 
   - containerPort: 9981
---
apiVersion: v1
kind: Service
metadata:
    name: websvc2
    namespace: test-ns
spec:
  type: NodePort
  selector:
        app: nodejs
  ports:
  - port: 80
    targetPort: 9981
