apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nodejsrs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      name:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: dockerhandson/node-app-mss:3
        ports:
        - containerPort: 9981
---
apiVersion: v1
kind: Service
metadata:
  name: nodejss
spec:
  selector:
    app: nodejs
  type: NodePort
  ports:
    - port: 80
      targetPort: 9981
