apiVersion: apps/v1
kind: Deployment
metadata:
   name: mavendeployment
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: Recreate
  selector:
     matchLabels:
        app: mavenweb
  template:
    metadata:
       name: mavenpod
       labels:
        app: mavenweb
    spec:
      affinity:
         nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 1
                preference:
                   matchExpressions:
                   - key: name 
                     operator: In
                     values:
                     - one
      containers:
      - name: webcontainer
        image:  dockerhandson/maven-web-application:1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
      name: websvc
spec:
  type: NodePort
  selector:
      app: mavenweb
  ports:
  - port: 80
    targetPort: 8080

