apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1Gi  # Adjust the size based on your requirements
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  # Adjust the access mode based on your requirements
  nfs:
    path: /mnt/nfs-share  # Replace with the actual path on your NFS server
    server: 10.128.0.57 # with the IP address or hostname of your NFS server  persistentVolumeReclaimPolicy: Retain

