apiVersion: v1
kind: ResourceQuota
metadata:
  name: resourcequota
  namespace: test-ns
spec:
  hard:
    pods: "3"
    requests.cpu: "3"
    requests.memory: 4Gi
    limits.cpu: "3"
    limits.memory: 4Gi

