apiVersion: apps/v1
kind: Deployment
metadata:
   name: mavendeployment
spec:
  replicas: 2
  revisionHistoryLimit: 10
  strategy:
    type: Recreate
  selector:
     matchLabels:
        app: mavenweb
  template:
    metadata:
       name: mavenpod
       labels:
        app: mavenweb
    spec:
      containers:
      - name: webcontainer
        image:  dockerhandson/maven-web-application:1
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /maven-web-application
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
      name: websvc
spec:
  type: NodePort
  selector:
      app: mavenweb
  ports:
  - port: 80
    targetPort: 8080

