apiVersion: apps/v1
kind: Deployment
metadata:
   name: springapp
   namespace: test-ns
spec:
  replicas: 2
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxUnavailable: 2
       maxSurge: 1
  minReadySeconds: 30
  selector:
     matchLabels:
        app: springboot
  template:
    metadata:
       name: springpod
       labels:
        app: springboot
    spec:
      containers:
      - name: springboot-container
        image:  dockerhandson/spring-boot-mongo:2
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DB_HOSTNAME
          value: mongodb-service
        - name: MONGO_DB_USERNAME
          value: devdb
        - name: MONGO_DB_PASSWORD
          value: devdb123
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
      name: springsvc
      namespace: test-ns
spec:
  type: NodePort
  selector:
      app: springboot
  ports:
  - port: 80
    targetPort: 8080
