apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp
  namespace: test-ns
spec:
  replicas: 2
  selector:
   matchLabels:
     app: springbootpod
  template:
    metadata:
      labels:
        app: springbootpod
    spec:
      containers:
      - name: springbootcontainer
        image: dockerhandson/spring-boot-mongo:2
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DB_HOSTNAME
          value: mongosvc
        - name: MONGO_DB_USERNAME
          valueFrom: 
            configMapKeyRef:
              name: springappconfig
              key: mongousername 
        - name: MONGO_DB_PASSWORD
          valueFrom: 
            configMapKeyRef:
              name: springappconfig
              key: mongodbpassword
---
apiVersion: v1
kind: Service
metadata:
   name: springsvc
   namespace: test-ns
spec:
  type: NodePort
  selector:
     app: springbootpod
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongodb
  namespace: test-ns
spec:
  selector:
     matchLabels:
        app: mongodb
  template:
    metadata:
      name: mongodbpod
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodbcontainer
        image: mongo
        ports:
          - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom: 
            configMapKeyRef:
              name: springappconfig
              key: mongousername
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            configMapKeyRef:
              name: springappconfig
              key: mongodbpassword
---
apiVersion: v1
kind: Service
metadata:
  name: mongosvc
  namespace: test-ns
spec:
  selector:
     app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
