
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpadeployment
	lebels:
	  name: hpdeployment
spec:
  replicas: 2
  selector:
     matchLabels:
       name: hpdelpoyment
  template:
   metadata:
     name: mavenpod
     labels:
      name: hpdelpoyment 
	 spec:
       containers:
       - name: hpacontainer
         image: k8s.gcr.io/hpa-example
         ports:
		 - name: http
         - containerPort:8080
       resources:
         requests:
           cpu: "100m"
           memory: "64Mi"
         limits:
          cpu: "100m"
          memory: "256Mi"
---		  
apiVersion: v1
kind: Service
metadata:
  name: hpasvc
spec:
  selector:
     name: hpdelpoyment 
  type: NodePort
  ports:
    - port: 80
      targetPort: 80