apiVersion: apps/v1
kind: Deployment
metadata:
  name: HPAdeployment
  labels:
   name: hpadeployment
spec:
 replicas: 2
 selector:
  matchLabels:
   name: hpadeployment
 template:
  metadata:
   name: mavenpod
   labels:
    name: hpadeployment
  spec:
   containers:
   - name: hpacontainer
     image: k8s.gcr.io/hpa-example
     ports:
     - name: http
       containerPort: 80
     resources:
      requests:
       cpu: "100m"
       memory: "64Mi"
      limits:
       cpu: "100m"
       memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
 name: hpasvc
spec:
 selector:
  name: hpadeployment
 type: NodePort
 ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v2
kind: HorizontalPodAutoscaler
metadata:
 name: hpa
spec:
 scaleTargetRef:
  apiversion: apps/v1
  kind: Deployment
  name: HPAdeployment
 minReplicas: 2
 maxReplicas: 5
 metrics:
  - type: Resources
    resource:
     name: cpu
     target:
      type: Uitilization
      averageUtilization: 40
  - type: Resources
    resource:
     name: memory
     target:
      type: Uitilization
      averageUtilization: 40      
